#mysql Connection
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: yourpassword
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 32772
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池总的最小空闲连接
        min-idle: 0
    timeout: 2000
    #cluster:
      #nodes: 127.0.0.1:32772


server:
  ssl:
    key-store: classpath:3719291_www.yichaotang.cn.pfx
    key-store-password: yIhTXlVx
